### ISSUE TITLE
CHECK in | Erro no método Post

### ISSUE THREAD

**Issue by eslinmakicine** [unisociesc/AgendaVoluntaria.Api#22]
Ao executar, o seguinte erro é retornado:

**500 Error: Internal Server Error**

AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.

Mapping types:
CheckRequest -> Attendance
AgendaVoluntaria.Api.Views.CheckRequest -> AgendaVoluntaria.Api.Models.Attendance
   at lambda_method(Closure , CheckRequest , Attendance , ResolutionContext )
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at AgendaVoluntaria.Api.Controllers.CheckController.In(CheckRequest request) in /src/src/AgendaVoluntaria.Api/Controllers/CheckController.cs:line 30
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Connection: close
Via: 1.1 vegur
Content-Type: application/json
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: pt-BR,pt;q=0.9,en;q=0.8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdobWV5ZXIwQGdtYWlsLmNvbSIsInJvbGUiOiJ2b2x1bnRlZXJzIiwiSWRVc2VyIjoiMDAwMjAwMDAtYWMxMS0wMjQyLWE5MjUtMDhkN2Q1MzY4ZDY5IiwibmJmIjoxNTg1NjY1NzU0LCJleHAiOjE1ODU4MTY5NTQsImlhdCI6MTU4NTY2NTc1NH0.zPnBI8fOLObvWN-Q6j1PcSS20ytqV2_ekiio9ExxTvA
Host: agendavoluntaria.herokuapp.com
Referer: https://agendavoluntaria.herokuapp.com/swagger/index.html
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
Origin: https://agendavoluntaria.herokuapp.com
Content-Length: 95
Sec-Fetch-Dest: empty
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
X-Request-Id: 7c945797-4924-4761-82ea-ee154aaf893a
X-Forwarded-For: 187.255.245.98
X-Forwarded-Proto: https
X-Forwarded-Port: 443
Connect-Time: 0
X-Request-Start: 1585667433875
Total-Route-Time: 0

**Comment by eslinmakicine** [comment]
@GHMeyer0  o erro persiste. 

System.NullReferenceException: Object reference not set to an instance of an object.
   at AgendaVoluntaria.Api.Services.AttendanceService.SaveCheckIn(Attendance attendance) in /src/src/AgendaVoluntaria.Api/Services/AttendanceService.cs:line 27
   at AgendaVoluntaria.Api.Controllers.CheckController.In(CheckRequest geolocalizacao) in /src/src/AgendaVoluntaria.Api/Controllers/CheckController.cs:line 36
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Connection: close
Via: 1.1 vegur
Content-Type: application/json
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: pt-BR,pt;q=0.9,en;q=0.8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlM0B0ZXN0ZTMuY29tIiwicm9sZSI6InZvbHVudGVlcnMiLCJJZFVzZXIiOiJlOWQxMDAwMC00NWI1LTk3Y2QtMDFiZi0wOGQ3ZDU4ODU5OTQiLCJuYmYiOjE1ODU2ODg3NTMsImV4cCI6MTU4NTgzOTk1MywiaWF0IjoxNTg1Njg4NzUzfQ.clBtTeiA12vJPK6_raF1mrv-7tS2B4UtmmEciv4cQZQ
Host: agendavoluntaria.herokuapp.com
Referer: https://agendavoluntaria.herokuapp.com/swagger/index.html
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
Origin: https://agendavoluntaria.herokuapp.com
Content-Length: 40
Sec-Fetch-Dest: empty
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
X-Request-Id: 7c8f86df-5202-4fcb-9456-b0ac15920b1f
X-Forwarded-For: 187.255.245.98
X-Forwarded-Proto: https
X-Forwarded-Port: 443
Connect-Time: 1
X-Request-Start: 1585747980930
Total-Route-Time: 0
