### ISSUE TITLE
CHECK out | Erro no método Post

### ISSUE THREAD

**Issue by eslinmakicine** [unisociesc/AgendaVoluntaria.Api#23]
O método retorna 200, no entanto, o retorno é:

{
  "title": "Check-In registrado!",
  "data": null
}

Corrigir o campo data e a mensagem para "Check-out registrado!".

**Comment by eslinmakicine** [comment]
@allanrodrigol quando executo, aparece o seguinte erro:

500

Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Npgsql.EntityFrameworkCore.PostgreSQL.Update.Internal.NpgsqlModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at AgendaVoluntaria.Api.Models.Context.SaveChangesAsync(CancellationToken cancellationToken) in /src/src/AgendaVoluntaria.Api/Models/Context.cs:line 56
   at AgendaVoluntaria.Api.Repositories.Core.CoreRepository`1.UpdateAsync(TEntity entity) in /src/src/AgendaVoluntaria.Api/Repositories/Base/CoreRepository.cs:line 74
   at AgendaVoluntaria.Api.Services.Core.CoreCrudService`2.UpdateAsync(TEntity entity) in /src/src/AgendaVoluntaria.Api/Services/Base/CoreCrudService.cs:line 51
   at AgendaVoluntaria.Api.Controllers.CheckController.Out(CheckRequest request) in /src/src/AgendaVoluntaria.Api/Controllers/CheckController.cs:line 47
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Cache-Control: no-cache
Connection: close
Via: 1.1 vegur
Content-Type: application/json
Accept: */*
Accept-Encoding: gzip, deflate, br
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlM0B0ZXN0ZTMuY29tIiwicm9sZSI6InZvbHVudGVlcnMiLCJJZFVzZXIiOiJlOWQxMDAwMC00NWI1LTk3Y2QtMDFiZi0wOGQ3ZDU4ODU5OTQiLCJuYmYiOjE1ODU2ODg3NTMsImV4cCI6MTU4NTgzOTk1MywiaWF0IjoxNTg1Njg4NzUzfQ.clBtTeiA12vJPK6_raF1mrv-7tS2B4UtmmEciv4cQZQ
Host: agendavoluntaria.herokuapp.com
User-Agent: PostmanRuntime/7.22.0
Content-Length: 50
Postman-Token: c5742590-71ca-4a36-a4d1-673519228bd1
X-Request-Id: 9e73a1eb-8150-464e-a178-6da3a783f3e1
X-Forwarded-For: 187.255.245.98
X-Forwarded-Proto: https
X-Forwarded-Port: 443
Connect-Time: 0
X-Request-Start: 1585748080117
Total-Route-Time: 0

**Comment by eslinmakicine** [comment]
@allanrodrigol  o erro relatado no comentário anterior persiste.
